import { AlertTriangle, ArrowUpRight, Check, ChevronRight, CircleDot, Clock3, Code2, FileCode2, GitBranch, LoaderCircle, LockKeyhole, Radar, RotateCcw, ShieldCheck, Terminal, X } from 'lucide-react';
import { Link } from 'wouter';
import type { ActivityEvent, Finding, Project, Scan, ScanStage } from '@workspace/api-client-react';
import { eventAccent, findingLabel, formatDate, formatDuration, initials, projectRepo, scanLabel, severityTone, statusTone } from '@/lib/kavach';

export function Logo() {
  return <Link href="/" className="k-focus flex items-center gap-3" data-testid="link-home"><span className="grid size-9 place-items-center rounded-lg border border-[hsl(var(--primary)/.45)] bg-[hsl(var(--primary)/.08)] text-[hsl(var(--primary))]"><ShieldCheck size={20} strokeWidth={1.8} /></span><span><strong className="block text-sm tracking-tight">AI KAVACH</strong><span className="k-eyebrow block mt-0.5">proof console</span></span></Link>;
}

export function Skeleton({ className = '' }: { className?: string }) { return <span className={`block k-pulse rounded-md bg-[hsl(var(--muted))] ${className}`} data-testid="loading-skeleton" />; }
export function LoadingState({ label = 'Loading evidence' }: { label?: string }) { return <div className="grid gap-3 p-8 text-center"><LoaderCircle className="mx-auto animate-spin text-[hsl(var(--primary))]" size={23} /><p className="k-mono text-xs text-[hsl(var(--muted-foreground))]">{label}</p></div>; }
export function ErrorState({ onRetry, label = 'Evidence feed unavailable' }: { onRetry?: () => void; label?: string }) { return <div className="grid gap-3 border border-[hsl(var(--destructive)/.3)] bg-[hsl(var(--destructive)/.06)] p-7 text-center rounded-lg"><AlertTriangle className="mx-auto text-[hsl(var(--destructive))]" size={22} /><p className="text-sm">{label}</p>{onRetry && <button className="k-button k-button-ghost mx-auto" onClick={onRetry} data-testid="button-retry"><RotateCcw size={14} /> Retry connection</button>}</div>; }
export function EmptyState({ icon: Icon = Radar, title, detail }: { icon?: typeof Radar; title: string; detail: string }) { return <div className="grid place-items-center gap-2 border border-dashed border-[hsl(var(--border))] p-10 text-center rounded-lg"><Icon className="text-[hsl(var(--muted-foreground))]" size={25} /><h3 className="text-sm font-semibold">{title}</h3><p className="max-w-sm text-xs leading-5 text-[hsl(var(--muted-foreground))]">{detail}</p></div>; }
export function StatusPill({ status }: { status?: string }) { return <span className={`k-pill ${statusTone(status)}`} data-testid={`status-${status}`}>{status?.replace('_', ' ') || 'unknown'}</span>; }
export function SeverityPill({ severity }: { severity: string }) { return <span className={`k-pill ${severityTone(severity)}`} data-testid={`severity-${severity}`}>{severity}</span>; }
export function PageHeader({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-4 k-reveal"><div><p className="k-eyebrow mb-2 text-[hsl(var(--primary))]">{eyebrow}</p><h1 className="text-2xl font-bold tracking-[-.04em] text-[hsl(var(--foreground))] md:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-[hsl(var(--muted-foreground))]">{detail}</p></div>{action}</div>; }
export function SectionTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { return <div className="mb-4 flex items-center justify-between gap-3"><div>{eyebrow && <p className="k-eyebrow mb-1">{eyebrow}</p>}<h2 className="text-sm font-semibold tracking-tight">{title}</h2></div>{action}</div>; }

export function ProjectCard({ project, onSelect }: { project: Project; onSelect?: () => void }) {
  return <button onClick={onSelect} className="k-card k-card-hover k-focus block w-full p-4 text-left" data-testid={`card-project-${project.id}`}><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-[hsl(var(--secondary))] font-bold text-sm text-[hsl(var(--primary))]">{initials(project.name)}</span><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{project.name}</h3><p className="k-mono mt-1 truncate text-[10px] text-[hsl(var(--muted-foreground))]">{projectRepo(project)}</p></div></div><StatusPill status={project.status} /></div><p className="mt-4 line-clamp-2 text-xs leading-5 text-[hsl(var(--muted-foreground))]">{project.description || 'Protected workspace with autonomous reasoning enabled.'}</p><div className="mt-4 flex items-center justify-between border-t border-[hsl(var(--border))] pt-3"><span className="flex items-center gap-1.5 text-[10px] text-[hsl(var(--muted-foreground))]"><GitBranch size={12} />{project.languages?.slice(0, 3).join(' · ') || 'Language map pending'}</span><span className="k-mono text-[10px] text-[hsl(var(--muted-foreground))]">{formatDate(project.lastScanAt)}</span></div></button>;
}

export function ScanRow({ scan }: { scan: Scan }) { return <Link href={`/scans/${scan.id}`} className="k-focus group grid grid-cols-[1fr_auto] gap-3 border-b border-[hsl(var(--border))] px-4 py-4 last:border-0 hover:bg-[hsl(var(--muted)/.3)]" data-testid={`link-scan-${scan.id}`}><div className="flex min-w-0 items-start gap-3"><span className={`mt-1 size-2 shrink-0 rounded-full ${scan.status === 'running' ? 'k-pulse bg-[hsl(var(--accent))]' : scan.status === 'failed' ? 'bg-[hsl(var(--destructive))]' : 'bg-[hsl(var(--primary))]'}`} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="k-mono text-xs text-[hsl(var(--primary))]">{scanLabel(scan)}</span><StatusPill status={scan.status} /></div><p className="mt-1 truncate text-sm font-medium">{scan.projectName || `Project ${scan.projectId}`}</p><p className="k-mono mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">{scan.stage} · {formatDate(scan.startedAt)}</p></div></div><div className="text-right"><p className="k-mono text-lg font-semibold">{scan.assuranceScore != null ? `${scan.assuranceScore}` : '—'}</p><p className="text-[10px] text-[hsl(var(--muted-foreground))]">{scan.findingCount} findings <ChevronRight className="ml-1 inline" size={12} /></p></div></Link>; }

export function ActivityList({ events }: { events: ActivityEvent[] }) { return <div className="divide-y divide-[hsl(var(--border))]">{events.map((event) => <div className="flex gap-3 py-3 first:pt-0 last:pb-0" key={event.id} data-testid={`activity-event-${event.id}`}><span className={`mt-1.5 size-2 shrink-0 rounded-full ${eventAccent(event.kind)}`} /><div className="min-w-0"><p className="text-xs leading-5">{event.message}</p><p className="mt-1 truncate text-[10px] text-[hsl(var(--muted-foreground))]">{event.detail} <span className="k-mono ml-1">{formatDate(event.createdAt)}</span></p></div></div>)}</div>; }

export function StageRail({ stages }: { stages: ScanStage[] }) { return <div className="grid gap-2 md:grid-cols-5">{stages.map((stage, index) => <div key={stage.key} className="relative rounded-md border border-[hsl(var(--border))] bg-[hsl(var(--muted)/.25)] p-3"><div className="mb-3 flex items-center justify-between"><span className={`grid size-6 place-items-center rounded-full ${statusTone(stage.status)} text-[10px] font-bold`}>{stage.status === 'complete' ? <Check size={13} /> : index + 1}</span><span className="k-mono text-[10px] text-[hsl(var(--muted-foreground))]">{formatDuration(stage.durationMs)}</span></div><p className="text-xs font-semibold">{stage.label}</p><p className="mt-1 text-[10px] leading-4 text-[hsl(var(--muted-foreground))]">{stage.detail}</p></div>)}</div>; }

export function FindingRow({ finding }: { finding: Finding }) { return <Link href={`/findings/${finding.id}`} className="k-focus group grid gap-3 border-b border-[hsl(var(--border))] px-4 py-4 last:border-0 md:grid-cols-[minmax(0,1.5fr)_110px_90px_80px]" data-testid={`link-finding-${finding.id}`}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="k-mono text-[10px] text-[hsl(var(--muted-foreground))]">{findingLabel(finding)}</span><SeverityPill severity={finding.severity} /><StatusPill status={finding.status} /></div><p className="mt-1 truncate text-sm font-medium group-hover:text-[hsl(var(--primary))]">{finding.title}</p><p className="k-mono mt-1 truncate text-[10px] text-[hsl(var(--muted-foreground))]">{finding.file}:{finding.line} · {finding.function}</p></div><div><p className="k-eyebrow">CWE</p><p className="k-mono mt-1 text-xs">{finding.cwe}</p></div><div><p className="k-eyebrow">confidence</p><p className="k-mono mt-1 text-xs">{finding.confidence}%</p></div><ArrowUpRight className="hidden self-center text-[hsl(var(--muted-foreground))] group-hover:text-[hsl(var(--primary))] md:block" size={16} /></Link>; }

export function ProofTile({ label, value }: { label: string; value: boolean }) { return <div className={`rounded-md border p-3 ${value ? 'border-[hsl(var(--primary)/.25)] bg-[hsl(var(--primary)/.06)]' : 'border-[hsl(var(--border))] bg-[hsl(var(--muted)/.22)]'}`}><div className="flex items-center justify-between gap-2"><span className="text-xs">{label}</span>{value ? <Check className="text-[hsl(var(--primary))]" size={15} /> : <X className="text-[hsl(var(--muted-foreground))]" size={15} />}</div><p className={`k-mono mt-2 text-[10px] uppercase ${value ? 'text-[hsl(var(--primary))]' : 'text-[hsl(var(--muted-foreground))]'}`}>{value ? 'confirmed' : 'not confirmed'}</p></div>; }

export function CodeBlock({ code, tone = 'neutral', label }: { code: string; tone?: 'neutral' | 'bad' | 'good'; label: string }) { return <div className={`overflow-hidden rounded-md border ${tone === 'bad' ? 'border-[hsl(var(--destructive)/.25)]' : tone === 'good' ? 'border-[hsl(var(--primary)/.25)]' : 'border-[hsl(var(--border))]'}`}><div className="flex items-center justify-between border-b border-[hsl(var(--border))] bg-[hsl(var(--muted)/.35)] px-3 py-2"><span className="k-mono text-[10px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">{label}</span><Code2 size={13} className="text-[hsl(var(--muted-foreground))]" /></div><pre className={`overflow-x-auto p-4 text-[11px] leading-6 ${tone === 'bad' ? 'bg-[hsl(var(--destructive)/.05)]' : tone === 'good' ? 'bg-[hsl(var(--primary)/.05)]' : 'bg-[hsl(var(--background))]'}`}><code>{code}</code></pre></div>; }